### ISSUE TITLE
About the train mode

### ISSUE THREAD

**Issue by Mapaler** [puzzled-dragon/pad-helper#13]
Thanks for your work.

I saw you add the train mode ,but it's not practical enough.
1. First I need a reset button to re-practice. 
2. Second calculate the number of hits display elimination animation.
3. Third if the orbs are obscured can be modified manually.  
So I still want to be able to combine it with manual mode.

**Comment by puzzled-dragon** [comment]
Oh dang.
It was not meant to get into the app yet.
It's just a preliminary work for the time being (based on the starting path mode)...
I will release a new version without the button for now.

It won't be released for a few weeks still.

I will take all your comments into account for the final version.
Thanks

**Comment by puzzled-dragon** [comment]
I don't think I will implement the "elimination animation" though.

For the moment, this is what I intend to implement in the v1 of the train mode : 
- Combo count (with type, shape, etc)
- Path length count
- Reset button
- Ability to modify the orbs (or maybe implement a bridge from the manual mode)
- Better line visual (closer to what is displayed normally)
- Ability to display the traced path on screen
- Ability to continue the search with the solver (similar to starting path mode)

**Comment by Mapaler** [comment]
# Also, please add the remaining numbers here
![](https://i.imgur.com/JIlDnDQ.jpg)

**Comment by puzzled-dragon** [comment]
Hi, this will be fixed in the next version!
