### ISSUE TITLE
Now it's time to add the Leader Skill details table page.

### ISSUE THREAD

**Issue by Mapaler** [puzzled-dragon/pad-helper#5]
Using the current mechanism, you can add a button to display the Leader Skill details, easy to understand the unused Leader Skills.

But now there are these problems:
* If it is read the source code and display, then how to display the picture?
* Whether can I use JavaScript to dynamically generate pages?
<hr>

Another question, I haven't developed the Android APP, so I don't understand that the Chinese language tag should be `zh-CN`, why it becomes `zh-rCN`.

For translators of other languages, you can display the current language tag in **Device Information**, and I think you should allow users to copy it (can't copy now).

**Comment by puzzled-dragon** [comment]
* Pictures can't be hosted on github, so it must be stored somewhere else (or fetched somehow).
* You can use JS, but I think you must stick to good old ES5. And I would prefer if JS was not prominent in the webviews.
---

Well, the resources in an Android App are stored in directory which are name, for example : `values-fr`, or `values-zh-rCN`, or `values-zh-rHK`, etc.
I do not know why there is a `r`, but I went with it !

I can change it if you want
